# permissions for end users to view dlpipejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dlpipejob-viewer-role
rules:
- apiGroups:
  - dlpipe.github.com
  resources:
  - dlpipejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dlpipe.github.com
  resources:
  - dlpipejobs/status
  verbs:
  - get
